/* Auto-generated by genmsg_cpp for file /home/tina/work/ros/sandbox/cram_morse_jido/morse_jido_manipulation_action/msg/arm_manipulationResult.msg */
#ifndef MORSE_JIDO_MANIPULATION_ACTION_MESSAGE_ARM_MANIPULATIONRESULT_H
#define MORSE_JIDO_MANIPULATION_ACTION_MESSAGE_ARM_MANIPULATIONRESULT_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"


namespace morse_jido_manipulation_action
{
template <class ContainerAllocator>
struct arm_manipulationResult_ : public ros::Message
{
  typedef arm_manipulationResult_<ContainerAllocator> Type;

  arm_manipulationResult_()
  : success(false)
  {
  }

  arm_manipulationResult_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


private:
  static const char* __s_getDataType_() { return "morse_jido_manipulation_action/arm_manipulationResult"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "358e233cde0c8a8bcfea4ce193f8fc15"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result\n\
bool success\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, success);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(success);
    return size;
  }

  typedef boost::shared_ptr< ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator>  const> ConstPtr;
}; // struct arm_manipulationResult
typedef  ::morse_jido_manipulation_action::arm_manipulationResult_<std::allocator<void> > arm_manipulationResult;

typedef boost::shared_ptr< ::morse_jido_manipulation_action::arm_manipulationResult> arm_manipulationResultPtr;
typedef boost::shared_ptr< ::morse_jido_manipulation_action::arm_manipulationResult const> arm_manipulationResultConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace morse_jido_manipulation_action

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "morse_jido_manipulation_action/arm_manipulationResult";
  }

  static const char* value(const  ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result\n\
bool success\n\
\n\
";
  }

  static const char* value(const  ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct arm_manipulationResult_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::morse_jido_manipulation_action::arm_manipulationResult_<ContainerAllocator> & v) 
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MORSE_JIDO_MANIPULATION_ACTION_MESSAGE_ARM_MANIPULATIONRESULT_H

