export PKG_CONFIG_PATH:=${PKG_CONFIG_PATH}:$(shell rospack find libmove3d)/lib/pkgconfig:$(shell rospack find gbM)/lib/pkgconfig:$(shell rospack find softmotion_libs)/lib/pkgconfig

include $(shell rospack find mk)/cmake.mk