(cl:defpackage morse_jido_manipulation_action-msg
  (:use )
  (:export
   "<ARM_MANIPULATIONACTIONFEEDBACK>"
   "ARM_MANIPULATIONACTIONFEEDBACK"
   "<ARM_MANIPULATIONACTION>"
   "ARM_MANIPULATIONACTION"
   "<ARM_MANIPULATIONFEEDBACK>"
   "ARM_MANIPULATIONFEEDBACK"
   "<ARM_MANIPULATIONACTIONGOAL>"
   "ARM_MANIPULATIONACTIONGOAL"
   "<ARM_MANIPULATIONRESULT>"
   "ARM_MANIPULATIONRESULT"
   "<ARM_MANIPULATIONACTIONRESULT>"
   "ARM_MANIPULATIONACTIONRESULT"
   "<ARM_MANIPULATIONGOAL>"
   "ARM_MANIPULATIONGOAL"
  ))

