; Auto-generated. Do not edit!


(cl:in-package morse_jido_manipulation_action-msg)


;//! \htmlinclude arm_manipulationGoal.msg.html

(cl:defclass <arm_manipulationGoal> (roslisp-msg-protocol:ros-message)
  ((joints
    :reader joints
    :initarg :joints
    :type sensor_msgs-msg:JointState
    :initform (cl:make-instance 'sensor_msgs-msg:JointState)))
)

(cl:defclass arm_manipulationGoal (<arm_manipulationGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <arm_manipulationGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'arm_manipulationGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name morse_jido_manipulation_action-msg:<arm_manipulationGoal> is deprecated: use morse_jido_manipulation_action-msg:arm_manipulationGoal instead.")))

(cl:ensure-generic-function 'joints-val :lambda-list '(m))
(cl:defmethod joints-val ((m <arm_manipulationGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader morse_jido_manipulation_action-msg:joints-val is deprecated.  Use morse_jido_manipulation_action-msg:joints instead.")
  (joints m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <arm_manipulationGoal>) ostream)
  "Serializes a message object of type '<arm_manipulationGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'joints) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <arm_manipulationGoal>) istream)
  "Deserializes a message object of type '<arm_manipulationGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'joints) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<arm_manipulationGoal>)))
  "Returns string type for a message object of type '<arm_manipulationGoal>"
  "morse_jido_manipulation_action/arm_manipulationGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'arm_manipulationGoal)))
  "Returns string type for a message object of type 'arm_manipulationGoal"
  "morse_jido_manipulation_action/arm_manipulationGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<arm_manipulationGoal>)))
  "Returns md5sum for a message object of type '<arm_manipulationGoal>"
  "13b568889983e6c4080c58d8e7c2c89c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'arm_manipulationGoal)))
  "Returns md5sum for a message object of type 'arm_manipulationGoal"
  "13b568889983e6c4080c58d8e7c2c89c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<arm_manipulationGoal>)))
  "Returns full string definition for message of type '<arm_manipulationGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%sensor_msgs/JointState joints~%~%================================================================================~%MSG: sensor_msgs/JointState~%# This is a message that holds data to describe the state of a set of torque controlled joints. ~%#~%# The state of each joint (revolute or prismatic) is defined by:~%#  * the position of the joint (rad or m),~%#  * the velocity of the joint (rad/s or m/s) and ~%#  * the effort that is applied in the joint (Nm or N).~%#~%# Each joint is uniquely identified by its name~%# The header specifies the time at which the joint states were recorded. All the joint states~%# in one message have to be recorded at the same time.~%#~%# This message consists of a multiple arrays, one for each part of the joint state. ~%# The goal is to make each of the fields optional. When e.g. your joints have no~%# effort associated with them, you can leave the effort array empty. ~%#~%# All arrays in this message should have the same size, or be empty.~%# This is the only way to uniquely associate the joint name with the correct~%# states.~%~%~%Header header~%~%string[] name~%float64[] position~%float64[] velocity~%float64[] effort~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'arm_manipulationGoal)))
  "Returns full string definition for message of type 'arm_manipulationGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%sensor_msgs/JointState joints~%~%================================================================================~%MSG: sensor_msgs/JointState~%# This is a message that holds data to describe the state of a set of torque controlled joints. ~%#~%# The state of each joint (revolute or prismatic) is defined by:~%#  * the position of the joint (rad or m),~%#  * the velocity of the joint (rad/s or m/s) and ~%#  * the effort that is applied in the joint (Nm or N).~%#~%# Each joint is uniquely identified by its name~%# The header specifies the time at which the joint states were recorded. All the joint states~%# in one message have to be recorded at the same time.~%#~%# This message consists of a multiple arrays, one for each part of the joint state. ~%# The goal is to make each of the fields optional. When e.g. your joints have no~%# effort associated with them, you can leave the effort array empty. ~%#~%# All arrays in this message should have the same size, or be empty.~%# This is the only way to uniquely associate the joint name with the correct~%# states.~%~%~%Header header~%~%string[] name~%float64[] position~%float64[] velocity~%float64[] effort~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.secs: seconds (stamp_secs) since epoch~%# * stamp.nsecs: nanoseconds since stamp_secs~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <arm_manipulationGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'joints))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <arm_manipulationGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'arm_manipulationGoal
    (cl:cons ':joints (joints msg))
))
