; Auto-generated. Do not edit!


(cl:in-package morse_jido_manipulation_action-msg)


;//! \htmlinclude arm_manipulationFeedback.msg.html

(cl:defclass <arm_manipulationFeedback> (roslisp-msg-protocol:ros-message)
  ((status
    :reader status
    :initarg :status
    :type cl:integer
    :initform 0))
)

(cl:defclass arm_manipulationFeedback (<arm_manipulationFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <arm_manipulationFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'arm_manipulationFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name morse_jido_manipulation_action-msg:<arm_manipulationFeedback> is deprecated: use morse_jido_manipulation_action-msg:arm_manipulationFeedback instead.")))

(cl:ensure-generic-function 'status-val :lambda-list '(m))
(cl:defmethod status-val ((m <arm_manipulationFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader morse_jido_manipulation_action-msg:status-val is deprecated.  Use morse_jido_manipulation_action-msg:status instead.")
  (status m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <arm_manipulationFeedback>) ostream)
  "Serializes a message object of type '<arm_manipulationFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'status)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <arm_manipulationFeedback>) istream)
  "Deserializes a message object of type '<arm_manipulationFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<arm_manipulationFeedback>)))
  "Returns string type for a message object of type '<arm_manipulationFeedback>"
  "morse_jido_manipulation_action/arm_manipulationFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'arm_manipulationFeedback)))
  "Returns string type for a message object of type 'arm_manipulationFeedback"
  "morse_jido_manipulation_action/arm_manipulationFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<arm_manipulationFeedback>)))
  "Returns md5sum for a message object of type '<arm_manipulationFeedback>"
  "86791dcf1de997ec7de5a0de7e4dcfcc")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'arm_manipulationFeedback)))
  "Returns md5sum for a message object of type 'arm_manipulationFeedback"
  "86791dcf1de997ec7de5a0de7e4dcfcc")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<arm_manipulationFeedback>)))
  "Returns full string definition for message of type '<arm_manipulationFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback -1:failure, 1: proceed the action, 2:success~%int32 status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'arm_manipulationFeedback)))
  "Returns full string definition for message of type 'arm_manipulationFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback -1:failure, 1: proceed the action, 2:success~%int32 status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <arm_manipulationFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <arm_manipulationFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'arm_manipulationFeedback
    (cl:cons ':status (status msg))
))
