; Auto-generated. Do not edit!


(cl:in-package morse_jido_manipulation_action-msg)


;//! \htmlinclude arm_manipulationResult.msg.html

(cl:defclass <arm_manipulationResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass arm_manipulationResult (<arm_manipulationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <arm_manipulationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'arm_manipulationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name morse_jido_manipulation_action-msg:<arm_manipulationResult> is deprecated: use morse_jido_manipulation_action-msg:arm_manipulationResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <arm_manipulationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader morse_jido_manipulation_action-msg:success-val is deprecated.  Use morse_jido_manipulation_action-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <arm_manipulationResult>) ostream)
  "Serializes a message object of type '<arm_manipulationResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <arm_manipulationResult>) istream)
  "Deserializes a message object of type '<arm_manipulationResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<arm_manipulationResult>)))
  "Returns string type for a message object of type '<arm_manipulationResult>"
  "morse_jido_manipulation_action/arm_manipulationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'arm_manipulationResult)))
  "Returns string type for a message object of type 'arm_manipulationResult"
  "morse_jido_manipulation_action/arm_manipulationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<arm_manipulationResult>)))
  "Returns md5sum for a message object of type '<arm_manipulationResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'arm_manipulationResult)))
  "Returns md5sum for a message object of type 'arm_manipulationResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<arm_manipulationResult>)))
  "Returns full string definition for message of type '<arm_manipulationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'arm_manipulationResult)))
  "Returns full string definition for message of type 'arm_manipulationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <arm_manipulationResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <arm_manipulationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'arm_manipulationResult
    (cl:cons ':success (success msg))
))
